module.exports = 
{
     ROLE_HARVESTER:0
    ,ROLE_UPGRADER:1
    ,ROLE_EXPLORER:2
    ,ROLE_BUILDER:3
    ,ROLE_FIGHTER:4
    ,ROLE_REPAIRER:5
    ,ROLE_STATIC_HARVESTER:6
    ,ROLE_EXPANDER:7
    ,ROLE_TRUCK:8
    ,ROLE_HARASSER:9
    ,ROLE_HAULER:10
    ,ROLE_REFILLER:11
    ,ROLE_STORAGE_LINK:12
    ,ROLE_SCOUT:13
};