module.exports = 
{
     ROLE_HARVESTER:0
    ,ROLE_UPGRADER:1
    ,ROLE_EXPLORER:2
    ,ROLE_BUILDER:3
    ,ROLE_FIGHTER:4
    ,ROLE_REPAIRER:5
    ,ROLE_STATIC_HARVESTER:6
    ,ROLE_EXPANDER:7
    ,ROLE_TRUCK:8
    ,ROLE_HARASSER:9
    ,ROLE_HAULER:10
    ,ROLE_REFILLER:11
    ,ROLE_STORAGE_LINK:12
    ,ROLE_SCOUT:13
    ,ROLE_RESERVER:14
    ,ROLE_TERMINAL_DUMPER:15
    
    ,REACTIONS:
    {
        RESOURCE_HYDROGEN: [],
        RESOURCE_OXYGEN: [],
        RESOURCE_UTRIUM: [],
        RESOURCE_LEMERGIUM: [],
        RESOURCE_KEANIUM: [],
        RESOURCE_ZYNTHIUM: [],
        RESOURCE_CATALYST: [],

        RESOURCE_GHODIUM: [RESOURCE_ZYNTHIUM_KEANITE, RESOURCE_UTRIUM_LEMERGITE],

        RESOURCE_HYDROXIDE: [RESOURCE_OXYGEN, RESOURCE_HYDROGEN],
        RESOURCE_ZYNTHIUM_KEANITE: [RESOURCE_ZYNTHIUM, RESOURCE_KEANIUM],
        RESOURCE_UTRIUM_LEMERGITE: [RESOURCE_UTRIUM, RESOURCE_LEMERGIUM],

        RESOURCE_UTRIUM_HYDRIDE: [RESOURCE_UTRIUM, RESOURCE_HYDROGEN],
        RESOURCE_UTRIUM_OXIDE: [RESOURCE_UTRIUM, RESOURCE_OXYGEN],
        RESOURCE_KEANIUM_HYDRIDE: [RESOURCE_KEANIUM, RESOURCE_HYDROGEN],
        RESOURCE_KEANIUM_OXIDE: [RESOURCE_KEANIUM, RESOURCE_OXYGEN],
        RESOURCE_LEMERGIUM_HYDRIDE: [RESOURCE_LEMERGIUM, RESOURCE_HYDROGEN],
        RESOURCE_LEMERGIUM_OXIDE: [RESOURCE_LEMERGIUM, RESOURCE_OXYGEN],
        RESOURCE_ZYNTHIUM_HYDRIDE: [RESOURCE_ZYNTHIUM, RESOURCE_HYDROGEN],
        RESOURCE_ZYNTHIUM_OXIDE: [RESOURCE_ZYNTHIUM, RESOURCE_OXYGEN],
        RESOURCE_GHODIUM_HYDRIDE: [RESOURCE_GHODIUM, RESOURCE_HYDROGEN],
        RESOURCE_GHODIUM_OXIDE: [RESOURCE_GHODIUM, RESOURCE_OXYGEN],
    
        RESOURCE_UTRIUM_ACID: [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        RESOURCE_UTRIUM_ALKALIDE: [RESOURCE_UTRIUM_OXIDE, RESOURCE_HYDROXIDE],
        RESOURCE_KEANIUM_ACID: [RESOURCE_KEANIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        RESOURCE_KEANIUM_ALKALIDE: [RESOURCE_KEANIUM_OXIDE, RESOURCE_HYDROXIDE],
        RESOURCE_LEMERGIUM_ACID: [RESOURCE_LEMERGIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        RESOURCE_LEMERGIUM_ALKALIDE: [RESOURCE_LEMERGIUM_OXIDE, RESOURCE_HYDROXIDE],
        RESOURCE_ZYNTHIUM_ACID: [RESOURCE_ZYNTHIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        RESOURCE_ZYNTHIUM_ALKALIDE: [RESOURCE_ZYNTHIUM_OXIDE, RESOURCE_HYDROXIDE],
        RESOURCE_GHODIUM_ACID: [RESOURCE_GHODIUM_HYDRIDE, RESOURCE_HYDROXIDE],
        RESOURCE_GHODIUM_ALKALIDE: [RESOURCE_GHODIUM_OXIDE, RESOURCE_HYDROXIDE],
    
        RESOURCE_CATALYZED_UTRIUM_ACID: [RESOURCE_UTRIUM_ACID, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_UTRIUM_ALKALIDE: [RESOURCE_UTRIUM_ALKALIDE, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_KEANIUM_ACID: [RESOURCE_KEANIUM_ACID, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_KEANIUM_ALKALIDE: [RESOURCE_KEANIUM_ALKALIDE, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_LEMERGIUM_ACID: [RESOURCE_LEMERGIUM_ACID, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE: [RESOURCE_LEMERGIUM_ALKALIDE, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_ZYNTHIUM_ACID: [RESOURCE_ZYNTHIUM_ACID, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE: [RESOURCE_ZYNTHIUM_ALKALIDE, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_GHODIUM_ACID: [RESOURCE_GHODIUM_ACID, RESOURCE_CATALYST],
        RESOURCE_CATALYZED_GHODIUM_ALKALIDE: [RESOURCE_GHODIUM_ALKALIDE, RESOURCE_CATALYST]
    }
};